name: CI - Users Service

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ§ª Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¦ Instalar dependÃªncias
        run: npm install

      - name: ğŸ§ª Rodar testes com cobertura
        run: |
          npm test
        env:
          JWT_SECRET: testsecret

      - name: ğŸ§¾ Salvar cobertura no GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: ğŸ› ï¸ Build do projeto
        run: npm run build

      - name: ğŸš€ Emular Deploy
        run: echo "Emulando deploy de produÃ§Ã£o..."